"""Ordered, immutable schema migrations for the TGrid database.

Each :class:`Migration` holds a ``version``, a ``name``, and an ordered tuple of
SQL statements.  ``MAX_SCHEMA_VERSION`` is the highest supported version and is
used to reject databases whose on-disk ``PRAGMA user_version`` (or migration
history) is newer than this build — we never auto-downgrade.

Migration 1 is the bootstrap: it creates the two Gate-0 foundation tables only
(``schema_migrations`` and ``application_metadata``).  No trading domain tables
(``t_lots``, orders, trades, positions, reservations) are created here; those
belong to Gate 2.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple

# Statements are static SQL strings.  Timestamps recorded by the migration
# runner (schema_migrations.applied_at) are generated by the runner itself;
# application_metadata.updated_at uses SQLite's own UTC clock for atomicity
# within the bootstrap transaction.
BOOTSTRAP_STATEMENTS: Tuple[str, ...] = (
    "CREATE TABLE schema_migrations ("
    " version INTEGER PRIMARY KEY CHECK(version > 0),"
    " name TEXT NOT NULL UNIQUE,"
    " applied_at TEXT NOT NULL"
    ")",
    "CREATE TABLE application_metadata ("
    " key TEXT PRIMARY KEY,"
    " value TEXT NOT NULL,"
    " updated_at TEXT NOT NULL"
    ")",
    "INSERT INTO application_metadata (key, value, updated_at)"
    " VALUES ('project_name', 'TGrid', datetime('now'))",
)


@dataclass(frozen=True)
class Migration:
    version: int
    name: str
    statements: Tuple[str, ...]


MIGRATIONS: Tuple[Migration, ...] = (
    Migration(version=1, name="bootstrap", statements=BOOTSTRAP_STATEMENTS),
)

MAX_SCHEMA_VERSION: int = max(migration.version for migration in MIGRATIONS)
