"""Ordered, immutable schema migrations for the TGrid database.

Each :class:`Migration` holds a ``version``, a ``name``, and an ordered tuple of
SQL statements.  ``MAX_SCHEMA_VERSION`` is the highest supported version and is
used to reject databases whose on-disk ``PRAGMA user_version`` (or migration
history) is newer than this build — we never auto-downgrade.

Migration 1 is the bootstrap: it creates the two Gate-0 foundation tables only
(``schema_migrations`` and ``application_metadata``).

Migration 2 creates the Gate-2 T-Lot Ledger foundation: the ``t_lots`` table with
database-level constraints (design §6 + §16.1 suspended review fields) and a
trigger that forbids ``DELETE FROM t_lots`` so historical lots can never be
silently removed.

Migration 3 creates the append-only ``t_lot_audit_log`` table (design §6 "all
state changes must be recorded by an Audit Log"): every audit row is immutable —
triggers forbid both ``UPDATE`` and ``DELETE`` — and ``t_lot_id`` must reference
an existing ``t_lots`` row so no event can ever dangle.

Migration 4 creates the Gate-4 execution foundation: ``order_intents``
(client_order_key idempotency, design §18.2) and ``order_reservations``
(position/cash reservation, design §18.3).  Both are append-mostly: an intent
is never deleted and a reservation is only released via ``released_at``.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Tuple

# Statements are static SQL strings.  Timestamps recorded by the migration
# runner (schema_migrations.applied_at) are generated by the runner itself;
# application_metadata.updated_at uses SQLite's own UTC clock for atomicity
# within the bootstrap transaction.
BOOTSTRAP_STATEMENTS: Tuple[str, ...] = (
    "CREATE TABLE schema_migrations ("
    " version INTEGER PRIMARY KEY CHECK(version > 0),"
    " name TEXT NOT NULL UNIQUE,"
    " applied_at TEXT NOT NULL"
    ")",
    "CREATE TABLE application_metadata ("
    " key TEXT PRIMARY KEY,"
    " value TEXT NOT NULL,"
    " updated_at TEXT NOT NULL"
    ")",
    "INSERT INTO application_metadata (key, value, updated_at)"
    " VALUES ('project_name', 'TGrid', datetime('now'))",
)

# Design §6 allowed statuses (single shared source of truth: the CHECK
# constraints and the offline writer both consume this; do not add a second
# drifting list).
T_LOT_STATUSES: Tuple[str, ...] = (
    "PENDING_BUY",
    "OPEN",
    "PENDING_SELL",
    "CLOSED",
    "SUSPENDED",
    "CONVERTED_TO_STRATEGIC",
    "ERROR",
)

# SQL-quoted literals for the CHECK constraints.
_T_LOT_STATUSES = tuple("'" + status + "'" for status in T_LOT_STATUSES)

# t_lots (design §6 fields + §16.1 suspended review fields).  Storage-class
# semantics are enforced at the database level: id/required texts are non-empty,
# qty must be a true SQLite integer > 0, prices must be a numeric (integer/real)
# storage class and positive when present, realized_pnl may be any numeric
# (losses/zero/gains) and fees must be a non-negative numeric.  Text values can
# never exploit storage-class ordering to bypass a CHECK.  No DELETE is ever
# allowed.
T_LOT_LEDGER_STATEMENTS: Tuple[str, ...] = (
    "CREATE TABLE t_lots ("
    " id TEXT NOT NULL PRIMARY KEY CHECK(length(trim(id)) > 0),"
    " symbol TEXT NOT NULL CHECK(length(trim(symbol)) > 0),"
    " side TEXT NOT NULL CHECK(length(trim(side)) > 0),"
    " qty INTEGER NOT NULL CHECK(typeof(qty) = 'integer' AND qty > 0),"
    " entry_price REAL NOT NULL CHECK(typeof(entry_price) IN ('integer', 'real')"
    " AND entry_price > 0),"
    " entry_time TEXT NOT NULL CHECK(length(trim(entry_time)) > 0),"
    " target_price REAL CHECK(target_price IS NULL OR (typeof(target_price) IN"
    " ('integer', 'real') AND target_price > 0)),"
    " grid_pct REAL CHECK(grid_pct IS NULL OR (typeof(grid_pct) IN ('integer',"
    " 'real') AND grid_pct > 0)),"
    " status TEXT NOT NULL CHECK(status IN (" + ", ".join(_T_LOT_STATUSES) + ")),"
    " exit_price REAL CHECK(exit_price IS NULL OR (typeof(exit_price) IN"
    " ('integer', 'real') AND exit_price > 0)),"
    " exit_time TEXT,"
    " entry_order_id TEXT,"
    " exit_order_id TEXT,"
    " realized_pnl REAL CHECK(realized_pnl IS NULL OR typeof(realized_pnl) IN"
    " ('integer', 'real')),"
    " fees REAL CHECK(fees IS NULL OR (typeof(fees) IN ('integer', 'real')"
    " AND fees >= 0)),"
    " created_at TEXT NOT NULL CHECK(length(trim(created_at)) > 0),"
    " updated_at TEXT NOT NULL CHECK(length(trim(updated_at)) > 0),"
    " suspended_at TEXT,"
    " review_due_at TEXT,"
    " last_reviewed_at TEXT,"
    " review_reason TEXT,"
    " review_status TEXT CHECK(review_status IS NULL OR review_status IN "
    " ('PENDING', 'RESUME_T', 'KEEP_SUSPENDED', 'CONVERT_TO_STRATEGIC', 'MANUAL_EXIT'))"
    ")",
    # Forbid any DELETE of a T-Lot: history is never removed.  State changes
    # must be recorded by future Audit Log updates.
    "CREATE TRIGGER t_lots_no_delete "
    "BEFORE DELETE ON t_lots "
    "BEGIN "
    " SELECT RAISE(ABORT, 't_lots rows cannot be deleted'); "
    "END",
)


# Append-only T-Lot Audit Log (design §6 "all state changes must be recorded by
# an Audit Log"; §7.1 Corporate Action adjustments are written here as JSON
# payloads whose business schema is decoded by a future writer/service).  Every
# audit row is immutable and must reference an existing t_lots row.
T_LOT_AUDIT_LOG_STATEMENTS: Tuple[str, ...] = (
    "CREATE TABLE t_lot_audit_log ("
    " id TEXT NOT NULL PRIMARY KEY CHECK(length(trim(id)) > 0),"
    " t_lot_id TEXT NOT NULL CHECK(length(trim(t_lot_id)) > 0)"
    " REFERENCES t_lots(id),"
    " event_type TEXT NOT NULL CHECK(length(trim(event_type)) > 0),"
    " from_status TEXT CHECK(from_status IS NULL OR from_status IN ("
    + ", ".join(_T_LOT_STATUSES) + ")),"
    " to_status TEXT CHECK(to_status IS NULL OR to_status IN ("
    + ", ".join(_T_LOT_STATUSES) + ")),"
    " details_json TEXT NOT NULL CHECK(length(trim(details_json)) > 0),"
    " actor TEXT NOT NULL CHECK(length(trim(actor)) > 0),"
    " created_at TEXT NOT NULL CHECK(length(trim(created_at)) > 0)"
    ")",
    # History events are append-only: no UPDATE and no DELETE may ever touch an
    # existing audit row; future services record state changes as new rows.
    "CREATE TRIGGER t_lot_audit_log_no_update "
    "BEFORE UPDATE ON t_lot_audit_log "
    "BEGIN "
    " SELECT RAISE(ABORT, 't_lot_audit_log rows are immutable'); "
    "END",
    "CREATE TRIGGER t_lot_audit_log_no_delete "
    "BEFORE DELETE ON t_lot_audit_log "
    "BEGIN "
    " SELECT RAISE(ABORT, 't_lot_audit_log rows cannot be deleted'); "
    "END",
)


# Gate 4 order intents (design §18.2): a durable, idempotent order intent is
# written BEFORE any broker send; client_order_key is the unique idempotency
# key; status moves READY_TO_SEND -> SUBMITTED -> PARTIAL/FILLED/REJECTED/
# CANCELED/UNKNOWN.  strategy_name/order_remark are the §18 order tags.
ORDER_INTENT_STATEMENTS: Tuple[str, ...] = (
    "CREATE TABLE order_intents ("
    " client_order_key TEXT NOT NULL PRIMARY KEY"
    " CHECK(length(trim(client_order_key)) > 0),"
    " symbol TEXT NOT NULL CHECK(length(trim(symbol)) > 0),"
    " side TEXT NOT NULL CHECK(side IN ('BUY', 'SELL')),"
    " qty INTEGER NOT NULL CHECK(typeof(qty) = 'integer' AND qty > 0),"
    " limit_price REAL NOT NULL CHECK(typeof(limit_price) IN ('integer', 'real')"
    " AND limit_price > 0),"
    " status TEXT NOT NULL CHECK(status IN ('NEW', 'READY_TO_SEND',"
    " 'SUBMITTED', 'PARTIAL', 'FILLED', 'CANCEL_REQUESTED', 'CANCELED',"
    " 'REJECTED', 'UNKNOWN')),"
    " strategy_name TEXT NOT NULL CHECK(length(trim(strategy_name)) > 0),"
    " order_remark TEXT NOT NULL CHECK(length(trim(order_remark)) > 0),"
    " broker_order_id TEXT,"
    " created_at TEXT NOT NULL CHECK(length(trim(created_at)) > 0),"
    " updated_at TEXT NOT NULL CHECK(length(trim(updated_at)) > 0)"
    ")",
    # Idempotency contract (INV-013): the client_order_key must be unique;
    # SQLite's PRIMARY KEY gives this.  No DELETE is ever allowed.
    "CREATE TRIGGER order_intents_no_delete "
    "BEFORE DELETE ON order_intents "
    "BEGIN "
    " SELECT RAISE(ABORT, 'order_intents rows cannot be deleted'); "
    "END",
)

# Gate 4 reservations (design §18.3): ReservedSellQty / ReservedCash are
# booked atomically with the OrderIntent that consumes them and released only
# against the true terminal order state.  A row records the side, the reserved
# quantity (shares for SELL, cash for BUY via amount) and the owning intent.
ORDER_RESERVATION_STATEMENTS: Tuple[str, ...] = (
    "CREATE TABLE order_reservations ("
    " id TEXT NOT NULL PRIMARY KEY CHECK(length(trim(id)) > 0),"
    " symbol TEXT NOT NULL CHECK(length(trim(symbol)) > 0),"
    " side TEXT NOT NULL CHECK(side IN ('BUY', 'SELL')),"
    " qty INTEGER NOT NULL CHECK(typeof(qty) = 'integer' AND qty > 0),"
    " cash_amount REAL CHECK(cash_amount IS NULL OR"
    " (typeof(cash_amount) IN ('integer', 'real') AND cash_amount >= 0)),"
    " client_order_key TEXT NOT NULL"
    " REFERENCES order_intents(client_order_key),"
    " created_at TEXT NOT NULL CHECK(length(trim(created_at)) > 0),"
    " released_at TEXT"
    ")",
    # A reservation is never deleted; it is released by setting released_at.
    "CREATE TRIGGER order_reservations_no_delete "
    "BEFORE DELETE ON order_reservations "
    "BEGIN "
    " SELECT RAISE(ABORT, 'order_reservations rows cannot be deleted'); "
    "END",
)

# Gate 5.5 durable daily exposure journal (NODEB-RR4-004): the hard daily
# cash-exposure cap is persisted per trade_date through the normal schema
# migration/verification lifecycle instead of an ad-hoc table.  One row per
# trade_date carries the submitted-BUY notional; the row is upserted by the
# exposure store and never deleted.
DAILY_EXPOSURE_STATEMENTS: Tuple[str, ...] = (
    "CREATE TABLE daily_exposure ("
    " trade_date TEXT NOT NULL PRIMARY KEY"
    " CHECK(length(trim(trade_date)) > 0),"
    " buy_notional REAL NOT NULL"
    " CHECK(typeof(buy_notional) IN ('integer', 'real')"
    " AND buy_notional >= 0)"
    ")",
    "CREATE TRIGGER daily_exposure_no_delete "
    "BEFORE DELETE ON daily_exposure "
    "BEGIN "
    " SELECT RAISE(ABORT, 'daily_exposure rows cannot be deleted'); "
    "END",
)


@dataclass(frozen=True)
class Migration:
    version: int
    name: str
    statements: Tuple[str, ...]


MIGRATIONS: Tuple[Migration, ...] = (
    Migration(version=1, name="bootstrap", statements=BOOTSTRAP_STATEMENTS),
    Migration(
        version=2, name="t_lot_ledger", statements=T_LOT_LEDGER_STATEMENTS
    ),
    Migration(
        version=3, name="t_lot_audit_log", statements=T_LOT_AUDIT_LOG_STATEMENTS
    ),
    Migration(
        version=4, name="order_intents", statements=ORDER_INTENT_STATEMENTS
    ),
    Migration(
        version=5, name="order_reservations", statements=ORDER_RESERVATION_STATEMENTS
    ),
    Migration(
        version=6, name="daily_exposure", statements=DAILY_EXPOSURE_STATEMENTS
    ),
)

MAX_SCHEMA_VERSION: int = max(migration.version for migration in MIGRATIONS)
